### ISSUE TITLE
feat: sanitise input of user

### ISSUE THREAD

**Issue by edisontim** [The-Overlore/lore-machine#102]
When receiving input of user on `generateDiscussion`, make sure to sanitize it.

**Comment by cwastche** [comment]
We are already protected from SQL injections because we use parameterized queries in Sqlite 3 (using "?" as placeholder for inserting data). Sqlite3 ensures that data passed this way to a query cannot be executed as code, or change the structure or execution flow of said query. 

In effect, when I tried to send a drop table injection, the given user input was simply inserted like any other plain text in our DB, without changing the query.
